import { FileStorageError, type FileStoragePort } from "./file-storage.port";
import { presignUrl, signRequest, uriEncode, type SigV4Credentials } from "./sigv4";

/** How to reach the bucket. Works for AWS S3 and for any S3-compatible store. */
export interface S3StorageConfig {
  /** Origin of the service, e.g. `https://s3.eu-central-1.amazonaws.com`. */
  readonly endpoint: string;
  readonly bucket: string;
  readonly region: string;
  readonly accessKeyId: string;
  readonly secretAccessKey: string;
  readonly sessionToken?: string;
  /**
   * `true` puts the bucket in the path (`{endpoint}/{bucket}/{key}`), which is
   * what MinIO, R2 and most self-hosted stores expect. `false` uses the
   * virtual-host form (`https://{bucket}.{host}/{key}`), AWS's default.
   */
  readonly forcePathStyle: boolean;
}

/** Injectable for tests; matches the shape of global `fetch`. */
export type FetchLike = (url: string, init: RequestInit) => Promise<Response>;

/**
 * S3-compatible object storage over plain `fetch`, signed with the self-built
 * SigV4 signer (EPIC-17 · M17.3).
 *
 * No vendor SDK: SigV4 and three REST calls are the whole surface an
 * application needs, and a hand-written signer keeps the dependency tree flat
 * (Engineering Standards §5.1). The signer is checked against AWS's published
 * test vectors in `sigv4.test.ts`.
 */
export class S3FileStorage implements FileStoragePort {
  private readonly credentials: SigV4Credentials;

  constructor(
    private readonly config: S3StorageConfig,
    private readonly fetchImpl: FetchLike = globalThis.fetch,
  ) {
    this.credentials = {
      accessKeyId: config.accessKeyId,
      secretAccessKey: config.secretAccessKey,
      region: config.region,
      ...(config.sessionToken === undefined ? {} : { sessionToken: config.sessionToken }),
    };
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    const { url, headers } = signRequest(this.credentials, {
      method: "PUT",
      url: this.objectUrl(key),
      headers: {
        "content-type": contentType,
        "content-length": String(body.byteLength),
      },
      body,
    });

    const response = await this.send(url, { method: "PUT", headers, body: new Uint8Array(body) });
    if (!response.ok) {
      throw new FileStorageError(
        `Storing object failed with status ${response.status}.`,
        response.status,
      );
    }
  }

  getSignedUrl(key: string, expiresInSeconds: number): Promise<string> {
    // Synchronous work, but the port is async so the adapter can be swapped
    // for one that has to call out (a KMS-backed signer, say).
    return Promise.resolve(
      presignUrl(this.credentials, {
        method: "GET",
        url: this.objectUrl(key),
        expiresInSeconds,
      }),
    );
  }

  async delete(key: string): Promise<void> {
    const { url, headers } = signRequest(this.credentials, {
      method: "DELETE",
      url: this.objectUrl(key),
      headers: {},
    });

    const response = await this.send(url, { method: "DELETE", headers });
    // S3 answers 204 for a delete, and the same for a key that was never
    // there; 404 from a compatible store means the same thing. Neither is a
    // failure — the caller wanted the object gone, and it is.
    if (!response.ok && response.status !== 404) {
      throw new FileStorageError(
        `Deleting object failed with status ${response.status}.`,
        response.status,
      );
    }
  }

  // ---- internals -------------------------------------------------------------

  private async send(url: string, init: RequestInit): Promise<Response> {
    try {
      return await this.fetchImpl(url, init);
    } catch (cause) {
      // A network failure is not something a caller can act on differently
      // from a rejection, so both arrive as FileStorageError.
      throw new FileStorageError(
        `Object storage is unreachable: ${cause instanceof Error ? cause.message : String(cause)}`,
      );
    }
  }

  /**
   * The absolute URL of one object.
   *
   * The key is validated before it is encoded, because percent-encoding does
   * not defuse a traversing key: `.` is an unreserved character, so `..`
   * survives encoding unchanged and both `fetch` and the store would then
   * normalize the path — addressing an object outside the prefix the caller
   * meant. Keys are generated by the application today, so a bad one is a bug
   * rather than an attack, and failing loudly is how it gets found.
   */
  private objectUrl(key: string): string {
    const segments = key.split("/");
    if (
      key === "" ||
      segments.some((segment) => segment === "" || segment === "." || segment === "..")
    ) {
      throw new FileStorageError(
        `Invalid object key '${key}': empty, '.' and '..' segments are not addressable.`,
      );
    }

    const encodedKey = segments.map((segment) => uriEncode(segment)).join("/");
    const endpoint = this.config.endpoint.replace(/\/+$/, "");

    if (this.config.forcePathStyle) {
      return `${endpoint}/${this.config.bucket}/${encodedKey}`;
    }
    const url = new URL(endpoint);
    return `${url.protocol}//${this.config.bucket}.${url.host}/${encodedKey}`;
  }
}
