import type {
  AcceptOutcome,
  CompanyRecord,
  InvitationRecord,
  MembershipCompany,
  MeProfileRow,
} from "./tenancy.types";

/**
 * Persistence port for tenancy. The application layer depends on this interface;
 * the Prisma-backed adapter lives in infrastructure (architecture test:
 * `data-access-only-in-infrastructure`).
 *
 * Isolation note: every operation binds the caller's principal (and, for tenant
 * writes, the target company) so RLS scopes it, in addition to the explicit
 * filters carried here — scoping is never trusted to one layer. Company creation
 * and invite acceptance run the M4.4 bootstrap path (user context, then the new
 * tenant bound) permitted by the widened RLS policies.
 */
export interface TenancyRepositoryPort {
  /** The caller's own profile fields for `/v1/me`, or null. */
  findProfile(userId: string): Promise<MeProfileRow | null>;

  /** Companies the caller belongs to (oldest membership first). */
  listUserCompanies(userId: string): Promise<MembershipCompany[]>;

  /**
   * Create a company and the caller's owner membership atomically. The company id
   * is generated by the caller so the owner row can be written under the new
   * tenant without depending on INSERT…RETURNING visibility. Throws
   * {@link SlugAlreadyTakenError} on a duplicate slug.
   */
  createCompanyWithOwner(input: {
    readonly companyId: string;
    readonly name: string;
    readonly slug: string | null;
    readonly userId: string;
  }): Promise<CompanyRecord>;

  /** The caller's active membership role in a company, or null if not an active member. */
  findActiveMembership(userId: string, companyId: string): Promise<{ role: string } | null>;

  /** Create a pending invitation in the given (active) tenant. */
  createInvitation(input: {
    readonly companyId: string;
    readonly email: string;
    readonly role: string;
    readonly codeHash: string;
    readonly expiresAt: Date;
    readonly actorId: string;
  }): Promise<InvitationRecord>;

  /** Revoke a pending invitation in the active tenant. Returns false if none matched. */
  revokeInvitation(input: {
    readonly companyId: string;
    readonly invitationId: string;
    readonly actorId: string;
  }): Promise<boolean>;

  /**
   * Accept an invitation by its code hash: resolve it (pre-tenant lookup), verify
   * it is live and addressed to the caller, then join the company and mark it
   * accepted — all atomically. Returns a typed outcome rather than throwing for
   * the expected rejection cases.
   */
  acceptInvitationByCode(input: {
    readonly codeHash: string;
    readonly userId: string;
    readonly email: string;
  }): Promise<AcceptOutcome>;
}

/** DI token for {@link TenancyRepositoryPort}. */
export const TENANCY_REPOSITORY = Symbol("TENANCY_REPOSITORY");
