import type {
  AcceptOutcome,
  AcceptWarehouseJoinCodeOutcome,
  CompanyRecord,
  InvitationRecord,
  MembershipCompany,
  MemberView,
  MeProfileRow,
  RemoveMemberOutcome,
} from "./tenancy.types";

/**
 * Persistence port for tenancy. The application layer depends on this interface;
 * the Prisma-backed adapter lives in infrastructure (architecture test:
 * `data-access-only-in-infrastructure`).
 *
 * Isolation note: every operation binds the caller's principal (and, for tenant
 * writes, the target company) so RLS scopes it, in addition to the explicit
 * filters carried here — scoping is never trusted to one layer. Company creation
 * and invite acceptance run the M4.4 bootstrap path (user context, then the new
 * tenant bound) permitted by the widened RLS policies.
 */
export interface TenancyRepositoryPort {
  /** The caller's own profile fields for `/v1/me`, or null. */
  findProfile(userId: string): Promise<MeProfileRow | null>;

  /** Companies the caller belongs to (oldest membership first). */
  listUserCompanies(userId: string): Promise<MembershipCompany[]>;

  /**
   * Create a company and the caller's owner membership atomically. The company id
   * is generated by the caller so the owner row can be written under the new
   * tenant without depending on INSERT…RETURNING visibility. Throws
   * {@link SlugAlreadyTakenError} on a duplicate slug.
   */
  createCompanyWithOwner(input: {
    readonly companyId: string;
    readonly name: string;
    readonly slug: string | null;
    readonly userId: string;
    readonly phone: string;
    readonly monthlyOrdersRange: string;
    readonly country: string | null;
    readonly facebookHandle: string | null;
    readonly instagramHandle: string | null;
    readonly websiteUrl: string | null;
    readonly shippingCarrier: string | null;
    readonly trialEndsAt: Date;
  }): Promise<CompanyRecord>;

  /** The caller's active membership role in a company, or null if not an active member. */
  findActiveMembership(userId: string, companyId: string): Promise<{ role: string } | null>;

  /** Update the WhatsApp dialing-prefix setting for a company. Returns null if the company is gone. */
  updateWhatsappCountryCode(
    companyId: string,
    actorId: string,
    countryCode: string | null,
  ): Promise<CompanyRecord | null>;

  /** Create a pending invitation in the given (active) tenant. */
  createInvitation(input: {
    readonly companyId: string;
    readonly role: string;
    /** Permission keys for a one-off "custom" role; omitted/empty for a template role. */
    readonly customPermissionKeys?: readonly string[];
    readonly codeHash: string;
    readonly expiresAt: Date;
    readonly actorId: string;
  }): Promise<InvitationRecord>;

  /** Revoke a pending invitation in the active tenant. Returns false if none matched. */
  revokeInvitation(input: {
    readonly companyId: string;
    readonly invitationId: string;
    readonly actorId: string;
  }): Promise<boolean>;

  /** Pending/recent invitations for the active tenant, newest first. */
  listInvitations(companyId: string): Promise<InvitationRecord[]>;

  /**
   * All permission keys available to the company given its current
   * subscription/features (independent of any member's role) — used to
   * validate a custom-role invitation's chosen permissions server-side.
   */
  listCompanyAvailablePermissionKeys(companyId: string): Promise<string[]>;

  /** Active members of the given (active) tenant, oldest membership first. */
  listMembers(companyId: string): Promise<MemberView[]>;

  /**
   * Remove an active member from the given (active) tenant. Refuses to remove
   * the company's last active Owner.
   */
  removeMember(input: {
    readonly companyId: string;
    readonly memberId: string;
    readonly actorId: string;
  }): Promise<RemoveMemberOutcome>;

  /**
   * Accept an invitation by its code hash: resolve it (pre-tenant lookup),
   * verify it is live, then join the company and mark it accepted — all
   * atomically. Returns a typed outcome rather than throwing for the expected
   * rejection cases. The code is the whole credential; it is not scoped to an
   * email address.
   */
  acceptInvitationByCode(input: {
    readonly codeHash: string;
    readonly userId: string;
  }): Promise<AcceptOutcome>;

  /**
   * Accept a warehouse join code by its hash (Vendor Accounts, Phase 1): same
   * pre-tenant lookup + atomic join shape as {@link acceptInvitationByCode},
   * but the resulting membership is always `role = "vendor"` scoped to the
   * code's warehouse.
   */
  acceptWarehouseJoinCodeByCode(input: {
    readonly codeHash: string;
    readonly userId: string;
  }): Promise<AcceptWarehouseJoinCodeOutcome>;
}

/** DI token for {@link TenancyRepositoryPort}. */
export const TENANCY_REPOSITORY = Symbol("TENANCY_REPOSITORY");
