/**
 * Auth domain types — pure data shapes with no framework or IO coupling. The
 * application layer orchestrates these; infrastructure adapters map them to/from
 * persistence.
 */
import type { TokenPair } from "../../../shared/contracts/token-pair";

/** A persisted user account, as the domain sees it. */
export interface ProfileRecord {
  readonly id: string;
  readonly email: string;
  /** Self-describing password hash (`@cadeau/crypto`); never the plaintext. */
  readonly passwordHash: string;
  readonly fullName: string | null;
  /** AES-GCM ciphertext token for the phone, or null; never plaintext PII. */
  readonly phoneEncrypted: string | null;
  /** AES-GCM ciphertext of the base32 TOTP secret, or null; never plaintext. */
  readonly totpSecretEncrypted: string | null;
  /** When 2FA was confirmed; null ⇒ enrolled-but-unconfirmed or off. */
  readonly totpEnabledAt: Date | null;
  readonly createdAt: Date;
}

/** A persisted refresh-token session (one row per refresh-token family). */
export interface SessionRecord {
  readonly id: string;
  readonly userId: string;
  readonly companyId: string | null;
  readonly familyId: string;
  /** Hash of the *current* refresh token in this family; never the token. */
  readonly refreshTokenHash: string;
  readonly userAgent: string | null;
  readonly ipAddress: string | null;
  readonly expiresAt: Date;
  readonly revokedAt: Date | null;
  readonly createdAt: Date;
}

/** Fields needed to create a profile (register). */
export interface NewProfile {
  readonly email: string;
  readonly passwordHash: string;
  readonly fullName: string | null;
  readonly phoneEncrypted: string | null;
}

/** Fields needed to open a session (login). */
export interface NewSession {
  /** Session id, generated by the service so it can be embedded in the token. */
  readonly id: string;
  readonly userId: string;
  readonly companyId: string | null;
  readonly familyId: string;
  readonly refreshTokenHash: string;
  readonly userAgent: string | null;
  readonly ipAddress: string | null;
  readonly expiresAt: Date;
}

/** The authenticated principal carried on a request once a token is verified. */
export interface Principal {
  readonly userId: string;
  readonly sessionId: string;
  /** Active tenant, or null until the user creates/joins a company (M4.4). */
  readonly companyId: string | null;
}

// The token-pair shape is a shared cross-feature contract; re-export it here so
// the rest of the auth slice keeps importing it from the domain unchanged.
export type { TokenPair } from "../../../shared/contracts/token-pair";

/** Contextual metadata captured with a sign-in, for the session record + audit. */
export interface RequestMeta {
  readonly userAgent: string | null;
  readonly ipAddress: string | null;
}

/** Public, non-sensitive view of a user (never carries the password hash). */
export interface UserSummary {
  readonly id: string;
  readonly email: string;
  readonly fullName: string | null;
}

/** Result of an authentication (register/login/refresh): the user + a token pair. */
export interface AuthResult {
  readonly user: UserSummary;
  readonly tokens: TokenPair;
}

/**
 * TOTP enrolment material, returned once when 2FA enrolment begins. The `secret`
 * and `otpauthUri` are shown to the user (typically as a QR code) so they can add
 * the account to an authenticator app; they are never persisted in plaintext.
 */
export interface TwoFactorEnrolment {
  readonly secret: string;
  readonly otpauthUri: string;
}

/** A session as shown to its owner (no token material). */
export interface SessionView {
  readonly id: string;
  /** True for the session the caller is currently authenticated with. */
  readonly current: boolean;
  readonly userAgent: string | null;
  readonly ipAddress: string | null;
  readonly createdAt: Date;
  readonly expiresAt: Date;
  readonly revokedAt: Date | null;
}
